---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: super-project-operator
  namespace: inf
objects:

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: splunkconnects.logging.ocp.io
  spec:
    group: logging.ocp.io
    names:
      kind: SplunkConnect
      listKind: SplunkConnectList
      plural: splunkconnects
      singular: splunkconnect
    scope: Namespaced
    subresources:
      status: {}
#    validation:
#      openAPIV3Schema:
#        type: object
#        x-kubernetes-preserve-unknown-fields: true
    versions:
      - name: v1
        served: true
        storage: true

- apiVersion: v1
  kind: Namespace
  metadata:
    name: splunk-connect-operator

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    namespace: splunk-connect-operator
    name: splunk-connect

- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: ClusterRoleBinding
  metadata:
    name: super-project-cluster-admin
  roleRef:
    name: cluster-admin
  subjects:
    - kind: ServiceAccount
      name: splunk-connect
      namespace: splunk-connect-operator
  userNames:
    - system:serviceaccount:super-project-operator:super-project

- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    namespace: splunk-connect-operator
    name: splunk-connect
  subjects:
    - kind: ServiceAccount
      name: splunk-connect
  roleRef:
    kind: Role
    name: splunk-connect
    apiGroup: rbac.authorization.k8s.io

- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    namespace: splunk-connect-operator
    creationTimestamp: null
    name: splunk-connect
  rules:
    - apiGroups:
        - ""
      resources:
        - pods
        - services
        - services/finalizers
        - endpoints
        - persistentvolumeclaims
        - events
        - configmaps
        - secrets
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - apps
      resources:
        - deployments
        - daemonsets
        - replicasets
        - statefulsets
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - monitoring.coreos.com
      resources:
        - servicemonitors
      verbs:
        - get
        - create
    - apiGroups:
        - apps
      resourceNames:
        - super-project
      resources:
        - deployments/finalizers
      verbs:
        - update
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
    - apiGroups:
        - apps
      resources:
        - replicasets
        - deployments
      verbs:
        - get
    - apiGroups:
        - automation.ocp.io
      resources:
        - '*'
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch

- apiVersion: "image.openshift.io/v1"
  kind: ImageStream
  metadata:
    namespace: splunk-connect-operator
    name: splunk-connect-operator
  spec:
    lookupPolicy:
      local: true

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: splunk-connect-operator
    name: splunk-connect-operator
    namespace: splunk-connect-operator
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: "splunk-connect-operator:latest"
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: ${GIT_BRANCH}
        uri: ${GIT_REPO}
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: "build/Dockerfile"
    successfulBuildsHistoryLimit: 5
    triggers:
      - type: ConfigChange

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: splunk-connect-operator
    namespace: splunk-connect-operator
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: splunk-connect-operator
    template:
      metadata:
        labels:
          name: splunk-connect-operator
      spec:
        serviceAccountName: splunk-connect
        containers:
          - name: ansible
            command:
              - /usr/local/bin/ao-logs
              - /tmp/ansible-operator/runner
              - stdout
            # Replace this with the built image name
            image: "docker-registry.default.svc:5000/splunk-connect-operator/splunk-connect-operator:latest"
            imagePullPolicy: "Always"
            volumeMounts:
              - mountPath: /tmp/ansible-operator/runner
                name: runner
                readOnly: true
          - name: operator
            # Replace this with the built image name
            image: "docker-registry.default.svc:5000/splunk-connect-operator/splunk-connect-operator:latest"
            imagePullPolicy: "Always"
            volumeMounts:
              - mountPath: /tmp/ansible-operator/runner
                name: runner
            env:
              - name: WATCH_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: OPERATOR_NAME
                value: "splunk-connect"
              - name: ANSIBLE_GATHERING
                value: explicit
        volumes:
          - name: runner
            emptyDir: {}

parameters:
  - name: GIT_REPO
    required: true

  - name: GIT_BRANCH
    required: true
    value: master
