apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      name: splunk-connect
  template:
    metadata:
      labels:
        name: splunk-connect
    spec:
      serviceAccountName: splunk-connect
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: "quay.io/openshift-operators/splunk-connect:latest"
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          image: "quay.io/openshift-operators/splunk-connect:latest"
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "splunk-connect"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
