kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: splunk-connect
subjects:
- kind: ServiceAccount
  name: splunk-connect
roleRef:
  kind: Role
  name: splunk-connect
  apiGroup: rbac.authorization.k8s.io
