---
apiVersion: v1
kind: "SecurityContextConstraints"
metadata:
  name: {{ meta.namespace }}-fluentd-privileged
  annotations:
    kubernetes.io/description: "SCC for Splunk - Fluentd log aggregation daemonset"
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
  - '*'
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
  - '*'
supplementalGroups:
  type: RunAsAny
users:
  - "system:serviceaccount:{{ meta.namespace }}:default"
volumes:
  - '*'