---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: splunk-kubernetes-logging
  namespace: {{ meta.namespace }}
  labels:
    app: "{{ label.app }}"
    engine: fluentd
    version: 1.2.0
spec:
  selector:
    matchLabels:
      app: "{{ label.app }}"
      version: 1.2.0
  template:
    metadata:
      labels:
        app: "{{ label.app }}"
        version: 1.2.0
      annotations: {}
    spec:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: splunk-fluentd-k8s-logs
          image: splunk/fluentd-hec:1.1.1
          imagePullPolicy: Always
          args:
            - "-c"
            - "/fluentd/etc/fluent.conf"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SPLUNK_HEC_HOST
              value: "{{ splunk_hec_protocol }}://{{ splunk_hec_host }}"

            - name: SPLUNK_HEC_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ secret_name }}"
                  key: splunk_hec_token

          securityContext:
            privileged: true
            runAsUser: 0
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: "/var/log"

            - name: varlibdockercontainers
              mountPath: "/var/lib/docker/containers"
              readOnly: true
            - name: journallogpath
              mountPath: "/run/log/journal"
              readOnly: true
            - name: "{{ configmap_name }}"
              mountPath: "/fluentd/etc"
            - name: "{{ secret_name }}"
              mountPath: "/fluentd/etc/splunk"
              readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: "/var/log"

        - name: varlibdockercontainers
          hostPath:
            path: "/var/lib/docker/containers"
        - name: journallogpath
          hostPath:
            path: "/run/log/journal"
        - name: "{{ configmap_name }}"
          configMap:
            name: "{{ configmap_name }}"
        - name: "{{ secret_name }}"
          secret:
            secretName: "{{ secret_name }}"