---
- name: Create secret with Splunc token
  k8s:
    state: present
    verify_ssl: "{{ k8s_validate_cert }}"
    api_version: "v1"
    definition:
          kind: Secret
          metadata:
            name: "{{ secret_name }}"
            namespace: "{{ meta.namespace }}"
          type: Opaque
          data:
            splunk_hec_token: "{{ hec_token_b64 }}"